export const STORE_OPTIONS = `Yogurtland Onboarding Demo Vendor
Yogurtland Silver Demo Vendor
Yogurtland Brink Demo Vendor
YOGURTLAND AVONDALE
YOGURTLAND CHANDLER
YOGURTLAND MESA - DANA PARK
YOGURTLAND CUPERTINO
YOGURTLAND TUSTIN
YOGURTLAND CERRITOS MALL
YOGURTLAND LAGUNA HILLS
YOGURTLAND SHERMAN OAKS
YOGURTLAND HUNTINGTON BEACH
YOGURTLAND SDSU
YOGURTLAND MIRACLE MILE
YOGURTLAND ARTESIA
YOGURTLAND COSTA MESA
YOGURTLAND UCI
YOGURTLAND FULLERTON DOWNTOWN
YOGURTLAND CHINO HILLS
YOGURTLAND ARCADIA
YOGURTLAND WEST COVINA
YOGURTLAND ANAHEIM HILLS
YOGURTLAND BREA
YOGURTLAND WESTGATE WEST
YOGURTLAND IRVINE
YOGURTLAND PLEASANT HILL
YOGURTLAND SANTA BARBARA
YOGURTLAND ANAHEIM
YOGURTLAND CULVER CITY
YOGURTLAND MIRA MESA
YOGURTLAND CLAREMONT
YOGURTLAND EVERGREEN VALLEY CENTER
YOGURTLAND RIVIERA PLACE
YOGURTLAND DANA POINT
YOGURTLAND DUBLIN WEST
YOGURTLAND MANHATTAN BEACH
YOGURTLAND LAKE FOREST
YOGURTLAND USC GATEWAY VILLAGE
YOGURTLAND RIVERSIDE CAMPUS
YOGURTLAND MILPITAS
YOGURTLAND RESEDA
YOGURTLAND PICO RIVERA
YOGURTLAND ENCINO
YOGURTLAND VILLAGE DEL AMO
YOGURTLAND LAKEWOOD
YOGURTLAND WESTLAKE VILLAGE
YOGURTLAND SIMI VALLEY
YOGURTLAND LA HABRA
YOGURTLAND ESCONDIDO
YOGURTLAND THE RIVER PARK AT FRESNO
YOGURTLAND WALNUT CREEK
YOGURTLAND CORONA
YOGURTLAND THE SHOPS AT ROSSMOOR
YOGURTLAND ATLANTIC SQUARE
YOGURTLAND STORY & KING ROAD
YOGURTLAND TARRAGONA PLAZA
YOGURTLAND SJSU
YOGURTLAND BAKERSFIELD RIVERWALK
YOGURTLAND CAPITOLA
YOGURTLAND CENTURY CITY MALL
YOGURTLAND GARDEN GROVE PLAZA
YOGURTLAND MIDTOWN
YOGURTLAND CAMP PENDLETON
YOGURTLAND AZUSA PLAZA
YOGURTLAND MONROVIA
YOGURTLAND THE VILLAGE AT ORANGE
YOGURTLAND WATSONVILLE
YOGURTLAND WILSHIRE & VERMONT
YOGURTLAND MIRA LOMA
YOGURTLAND SALINAS
YOGURTLAND VISALIA
YOGURTLAND GARDENA
YOGURTLAND SANTA ANA 17TH STREET
YOGURTLAND DOWNEY GATEWAY
YOGURTLAND GOLETA
YOGURTLAND BURBANK VICTORY BLVD.
YOGURTLAND MORENO VALLEY
YOGURTLAND FAIR OAKS
YOGURTLAND SAN GABRIEL PROMENADE
YOGURTLAND MISSION VIEJO
YOGURTLAND LYNWOOD PLAZA MEXICO
YOGURTLAND LAGUNA NIGUEL
YOGURTLAND SOUTH GATE
YOGURTLAND FLOWER HILL DEL MAR
YOGURTLAND FREMONT
YOGURTLAND FONTANA FALCON RIDGE
YOGURTLAND VERMONT & SANTA MONICA BLVD. HOLLYWOOD PLAZA
YOGURTLAND VALENCIA CROSSROADS
YOGURTLAND PASADENA LAKE AVENUE
YOGURTLAND CARSON SOUTHBAY PAVILLION
YOGURTLAND SAN DIMAS
YOGURTLAND LA VERNE FOOTHILL BLVD
YOGURTLAND TERRA VISTA TOWN CENTER
YOGURTLAND CAMDEN PARK SAN JOSE
YOGURTLAND EDINGER
YOGURTLAND CORONA HILLS PLAZA
YOGURTLAND GENESEE PLAZA
YOGURTLAND YORBA LINDA
YOGURTLAND PETALUMA
YOGURTLAND POMONA RIO RANCHO TOWN CENTER
YOGURTLAND WESTCHESTER
YOGURTLAND LA PALMA
YOGURTLAND BROKAW COMMONS
YOGURTLAND PALMDALE AVENUE P
YOGURTLAND PANORAMA CITY
YOGURTLAND NORWALK TOWNE SQUARE
YOGURTLAND CENTRAL SLAUSON - JUANITA TATE MARKETPLACE
YOGURTLAND INGLEWOOD
YOGURTLAND STONECREEK VILLAGE
YOGURTLAND MOUNTAIN VIEW
YOGURTLAND YUCAIPA
YOGURTLAND LAKE ELSINORE
YOGURTLAND VILLAGE OAKS SAN JOSE
YOGURTLAND FONTANA SIERRA AVENUE
YOGURTLAND IRVINE SPECTRUM
YOGURTLAND PAVILION AT LA QUINTA
YOGURTLAND TRUMAN STREET
YOGURTLAND THE SHOPS AT MONTEBELLO
YOGURTLAND EAGLE ROCK
YOGURTLAND BAKER
YOGURTLAND PARAMOUNT BLVD
YOGURTLAND MENIFEE
YOGURTLAND CENTRAL CHINO
YOGURTLAND ONTARIO
YOGURTLAND ALAMEDA LANDING
YOGURTLAND HESPERIA
YOGURTLAND WEST COVINA - AZUSA AND AMAR
YOGURTLAND COMPTON
YOGURTLAND LANCASTER
YOGURTLAND LONG BEACH - SPRING ST
YOGURTLAND MOUNTAIN GROVE
YOGURTLAND WALNUT
YOGURTLAND FIVE POINTS PLAZA
YOGURTLAND HAYWARD
YOGURTLAND GARDEN GROVE PROMENADE
YOGURTLAND WILSHIRE & UNION
YOGURTLAND BIXBY KNOLLS
YOGURTLAND TYLER RIVERSIDE
YOGURTLAND DESOTO & NORDHOFF
YOGURTLAND SANTA ANA- BRISTOL & SUNFLOWER
YOGURTLAND HUNTINGTON PARK
YOGURTLAND WEST HOLLYWOOD
YOGURTLAND NORTH HOLLYWOOD
YOGURTLAND BALDWIN HILLS
YOGURTLAND PERRIS MARKET PLACE
YOGURTLAND TUSTIN LEGACY
YOGURTLAND WOODBRIDGE
YOGURTLAND LA HABRA TOWN CENTER
YOGURTLAND APPLE VALLEY
YOGURTLAND SALTON CITY TRAVEL PLAZA
YOGURTLAND RIALTO
YOGURTLAND RANCHO MISSION VIEJO
YOGURTLAND ANAHEIM - KATELLA
YOGURTLAND ROWLAND HEIGHTS - COLIMA & FAIRWAY
YOGURTLAND HANFORD
YOGURTLAND BELMONT SHORE
YOGURTLAND FRESNO - EL PASEO
YOGURTLAND EAST PALMDALE - AVE S
YOGURTLAND SAN BERNARDINO
YOGURTLAND SAN CLEMENTE
Yogurtland Pasadena
YOGURTLAND RIVERSIDE
YOGURTLAND SANTA MONICA PROMENADE
Yogurtland-Beaumont
YOGURTLAND CHERRYWOOD SQUARE
YOGURTLAND 5TH & GRANT
YOGURTLAND GOVERNOR'S PLAZA
YOGURTLAND NORTHRIDGE CENTER
YOGURTLAND TOWNE CTR BATON ROUGE
YOGURTLAND SOUTHGATE AT LSU
YOGURTLAND LAFAYETTE
YOGURTLAND NEW ORLEANS
YOGURTLAND HAMILTON
Yogurtland West Berlin
YOGURTLAND LAS VEGAS TOWN SQUARE
YOGURTLAND WEST FLAMINGO
YOGURTLAND 215 & EASTERN
YOGURTLAND CENTENNIAL GATEWAY
YOGURTLAND WEST LAKE MEAD
YOGURTLAND HENDERSON STEPHANIE STREET
YOGURTLAND WINTERWOOD
YOGURTLAND 215 & N DECATUR
YOGURTLAND 215 & RAINBOW
YOGURTLAND LAS VEGAS FASHION SHOW FOOD COURT
YOGURTLAND Las Vegas - Boca Park
Yogurtland Las Vegas
Yogurtland Demo Vendor
YOGURTLAND CARROLLTON
YOGURTLAND SOUTHLAKE DFW
YOGURTLAND DALLAS NORTHWEST HWY
YOGURTLAND MONTGOMERY PLAZA
YOGURTLAND GARLAND FIREWHEEL TOWN CTR
YOGURTLAND MEMORIAL CITY MALL
YOGURTLAND FAIRFIELD TOWN CENTER
YOGURTLAND LAKE HIGHLANDS TOWN CENTER
YOGURTLAND WESTCHASE
YOGURTLAND FT. WORTH- WATERSIDE
YOGURTLAND PLANO
YOGURTLAND DALLAS - LAKEWOOD
YOGURTLAND SUGAR LAND
YOGURTLAND JORDAN LANDING
YOGURTLAND OREM
YOGURTLAND RED ROCK COMMONS`
  .split("\n")
  .map((v) => v.trim())
  .filter(Boolean);
